Fix build error like: - error TS2339: Property 'getWorkspaceFolder' does not exist on type 'typeof workspace'. - error TS6053: File '.../seito-openfile/node_modules/vscode/typings/node.d.ts' not found